version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: arkiver
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  arkiver:
    build:
      context: .
      dockerfile: docker/arkiver.Dockerfile
    environment:
      POSTGRES_URL: postgres://postgres:postgres@db:5432/arkiver
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - arkiver-sqlite:/app/db
    restart: always

  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    environment:
      POSTGRES_URL: postgres://postgres:postgres@db:5432/arkiver
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  arkiver-sqlite:
    driver: local
  arkiver-postgres:
    driver: local
