# fly.toml app configuration file generated for fortunes-roll-backend on 2023-12-18T07:36:40+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fortunes-roll-backend"
primary_region = "sea"

[build]

[env]
  SQLITE_URL = "sqlite3:///mnt/volume/production.sqlite3"

[[mounts]]
  source = "fortunes_arkiver_meta"
  destination = "/mnt/volume"
  auto_extend_size_threshold = 0

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
