[profile.default]
src = "src"
out = "out"
solc_version = "0.8.23"
libs = ["lib"]
via_ir = true
remappings = [
	"ds-test/=lib/forge-std/lib/ds-test/src/",
	"forge-std/=lib/forge-std/src/",
	"solmate/=lib/solmate/src/",
	"@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
